In [ ]:
'''DAY 5 — Real Data Cleaning + Missing Values

This is very important in Data Engineering.

Because real company data is often:

incomplete
messy
duplicated
inconsistent

Your job is to clean it.'''

In [2]:
import pandas as pd

df = pd.read_csv("employees.csv")
print(df)

    Name   Age   Salary Department
0   Josh  21.0  50000.0         AI
1   Alex   NaN  60000.0       Data
2   John  23.0      NaN      Cloud
3  Maria  22.0  55000.0        NaN
4   Sara  21.0  70000.0       Data
5   Josh  21.0  50000.0         AI

In [3]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False   False       False
5  False  False   False       False

In [4]:
df.isnull().sum()

Name          0
Age           1
Salary        1
Department    1
dtype: int64

In [9]:
age_avg = df["Age"].mean()
df["Age"] = df["Age"].fillna(age_avg)
print(df)

    Name   Age   Salary Department
0   Josh  21.0  50000.0         AI
1   Alex  21.6  60000.0       Data
2   John  23.0      NaN      Cloud
3  Maria  22.0  55000.0        NaN
4   Sara  21.0  70000.0       Data
5   Josh  21.0  50000.0         AI

In [11]:
avg_salary=df["Salary"].mean()
df["Salary"]=df["Salary"].fillna(avg_salary)
print(df)

    Name   Age   Salary Department
0   Josh  21.0  50000.0         AI
1   Alex  21.6  60000.0       Data
2   John  23.0  57000.0      Cloud
3  Maria  22.0  55000.0        NaN
4   Sara  21.0  70000.0       Data
5   Josh  21.0  50000.0         AI

In [12]:
df.drop_duplicates()

    Name   Age   Salary Department
0   Josh  21.0  50000.0         AI
1   Alex  21.6  60000.0       Data
2   John  23.0  57000.0      Cloud
3  Maria  22.0  55000.0        NaN
4   Sara  21.0  70000.0       Data

In [15]:
df.to_csv("cleaned_employees.csv", index=False)